/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name = actor.withobj.methodENDIF
		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("ioport | started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="press_button", cond=doswitch() )
				}	 

				// T1: prima richiesta → attesa load_accepted
				state("press_button") { //this:State
					action { //it:State
						CommUtils.outmagenta("customer -> ioport | pushbutton pressed")
						CommUtils.outcyan("ioport -> cargoservice | sending load_request [T1]")
						request("load_request", "loadRequest(none)", "cargoservice")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t0",targetState="accepted",cond=whenReply("load_accepted"))
				}	 
				state("accepted") { //this:State
					action { //it:State
						CommUtils.outgreen("ioport | DISPLAY: load accepted, reserved slot = slot1")
						delay(1000)  // pausa di 1 secondo tra le due richieste
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="press_button_2", cond=doswitch() )
				}	 

				// T3: seconda richiesta → cargoservice è engaged → load_refused
				state("press_button_2") { //this:State
					action { //it:State
						CommUtils.outmagenta("customer -> ioport | pushbutton pressed")
						CommUtils.outcyan("ioport -> cargoservice | sending load_request [T3 NUOVO - service engaged]")
						request("load_request", "loadRequest(none)", "cargoservice")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t1",targetState="refused",cond=whenReply("load_refused"))
					transition(edgeName="t2",targetState="retrylater",cond=whenReply("load_retrylater"))
				}	 
				state("refused") { //this:State
					action { //it:State
						CommUtils.outred("ioport | DISPLAY: load refused")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					// fine: nessuna transizione, il programma si ferma
				}	 
				state("retrylater") { //this:State
					action { //it:State
						CommUtils.outyellow("ioport | DISPLAY: retry later")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					// fine: nessuna transizione, il programma si ferma
				}	 
			}
		}
} 
