/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var ConnToRobotSmart : unibo.basicomm23.interfaces.Interaction? = null  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargorobot | STARTED (Puro wrapper bridge per robotsmart26)")
						 
						            try {
						                ConnToRobotSmart = unibo.basicomm23.mqtt.MqttConnection.create(
						                    "cargorobot_to_rs", "tcp://localhost:1883", "robotsmart26in"
						                )
						                println("cargorobot | Connesso via MQTT al topic robotsmart26in per robotsmart26") color green
						            } catch(e: Exception) {
						                println("cargorobot | ERRORE connessione iniziale a robotsmart26: ${e.message}") color red
						            }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_move",cond=whenRequest("moverobot"))
				}	 
				state("handle_move") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobot(TARGETX,TARGETY,STEPTIME)"), Term.createTerm("moverobot(X,Y,TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                val Tx = payloadArg(0)
								                val Ty = payloadArg(1)
								                val StepTime = payloadArg(2)
								                println("cargorobot | Inoltro comando moverobot($Tx, $Ty, $StepTime) a robotsmart26 via MQTT (robotsmart26in)...") color cyan
								                var replyStr = ""
								                try {
								                    if (ConnToRobotSmart == null) {
								                        ConnToRobotSmart = unibo.basicomm23.mqtt.MqttConnection.create(
								                            "cargorobot_to_rs", "tcp://localhost:1883", "robotsmart26in"
								                        )
								                    }
								                    val msgReq = unibo.basicomm23.utils.CommUtils.buildRequest("cargorobot", "moverobot", "moverobot($Tx,$Ty,$StepTime)", "robotsmart").toString()
								                    replyStr = ConnToRobotSmart!!.request(msgReq)
								                    println("cargorobot | Risposta da robotsmart26 via MQTT: $replyStr") color green
								                } catch(e: Exception) {
								                    println("cargorobot | Errore richiesta moverobot: ${e.message}") color red
								                }
								if(  replyStr.contains("moverobotok") || replyStr.contains("moverobotdone")  
								 ){answer("moverobot", "moverobotdone", "moverobotok(done)"   )  
								}
								else
								 {answer("moverobot", "moverobotfailed", "moverobotfailed(obstacle,0)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
