/* Generated by AN DISI Unibo */ 
package it.unibo.ioportmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioportmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outcyan("ioportmock | Sending 1st load_request (should be accepted)")
						request("load_request", "loadRequest(none)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handle_accept",cond=whenReply("load_accepted"))
					transition(edgeName="t02",targetState="handle_retry",cond=whenReply("load_retrylater"))
					transition(edgeName="t03",targetState="handle_refuse",cond=whenReply("load_refused"))
				}	 
				state("handle_accept") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						delay(12000) 
						CommUtils.outcyan("ioportmock | Sending 2nd load_request (should retrylater due to outofservice)")
						request("load_request", "loadRequest(none)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="wait_and_retry",cond=whenReply("load_retrylater"))
					transition(edgeName="t05",targetState="handle_final_accept",cond=whenReply("load_accepted"))
					transition(edgeName="t06",targetState="handle_refuse",cond=whenReply("load_refused"))
				}	 
				state("wait_and_retry") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						delay(6000) 
						CommUtils.outcyan("ioportmock | Sending 3rd load_request (should be accepted, system recovered)")
						request("load_request", "loadRequest(none)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="handle_final_accept",cond=whenReply("load_accepted"))
					transition(edgeName="t08",targetState="handle_retry",cond=whenReply("load_retrylater"))
					transition(edgeName="t09",targetState="handle_refuse",cond=whenReply("load_refused"))
				}	 
				state("handle_final_accept") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handle_retry") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handle_refuse") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
