/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var TargetX = ""
		        var TargetY = ""
		        var StepTime = ""
		        var Stopped = false
		        var MoveInProgress = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargorobot | STARTED (Puro wrapper bridge per robotsmart26)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outblue("cargorobot | In attesa di comandi moverobot...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_move",cond=whenRequest("moverobot"))
					transition(edgeName="t01",targetState="handle_stop",cond=whenDispatch("stop_robot"))
					transition(edgeName="t02",targetState="handle_resume",cond=whenDispatch("resume_robot"))
				}	 
				state("handle_move") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("moverobot(TARGETX,TARGETY,STEPTIME)"), Term.createTerm("moverobot(X,Y,TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								               val Tx = payloadArg(0) 
								               val Ty = payloadArg(1) 
								               val St = payloadArg(2) 
								               
								               TargetX = Tx
								               TargetY = Ty
								               StepTime = St
								               MoveInProgress = true
								if(  !Stopped  
								 ){CommUtils.outcyan("cargorobot | Inoltro moverobot($Tx, $Ty, $St) a robotsmart via TCP...")
								request("moverobot", "moverobot($Tx,$Ty,$St)" ,"robotsmart" )  
								}
								else
								 {CommUtils.outyellow("cargorobot | Ricevuto moverobot ma sono in STOP. Memorizzo e attendo resume.")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_reply", cond=doswitchGuarded({ !Stopped  
					}) )
					transition( edgeName="goto",targetState="waiting_resume", cond=doswitchGuarded({! ( !Stopped  
					) }) )
				}	 
				state("waiting_reply") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="forward_done",cond=whenReply("moverobotdone"))
					transition(edgeName="t04",targetState="forward_failed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t05",targetState="handle_stop",cond=whenDispatch("stop_robot"))
				}	 
				state("forward_done") { //this:State
					action { //it:State
						CommUtils.outgreen("cargorobot | robotsmart ha completato il movimento con successo!")
						 MoveInProgress = false  
						answer("moverobot", "moverobotdone", "moverobotok(done)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("forward_failed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val PlanDone = payloadArg(0)
								               val PlanTodo = payloadArg(1)  
								if(  Stopped  
								 ){CommUtils.outyellow("cargorobot | robotsmart ha interrotto il movimento causa STOP. Attendo resume...")
								}
								else
								 {CommUtils.outred("cargorobot | robotsmart ha FALLITO il movimento. Done=$PlanDone Todo=$PlanTodo")
								  MoveInProgress = false  
								 answer("moverobot", "moverobotfailed", "moverobotfailed($PlanDone,$PlanTodo)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_resume", cond=doswitchGuarded({ Stopped  
					}) )
					transition( edgeName="goto",targetState="waiting", cond=doswitchGuarded({! ( Stopped  
					) }) )
				}	 
				state("handle_stop") { //this:State
					action { //it:State
						CommUtils.outred("cargorobot | RICEVUTO STOP! Emetto alarm a robotsmart...")
						 Stopped = true  
						emit("alarm", "alarm(stop)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_reply", cond=doswitchGuarded({ MoveInProgress  
					}) )
					transition( edgeName="goto",targetState="waiting_resume", cond=doswitchGuarded({! ( MoveInProgress  
					) }) )
				}	 
				state("waiting_resume") { //this:State
					action { //it:State
						CommUtils.outyellow("cargorobot | In STOP. Attendo resume_robot...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="handle_resume",cond=whenDispatch("resume_robot"))
				}	 
				state("handle_resume") { //this:State
					action { //it:State
						CommUtils.outgreen("cargorobot | RICEVUTO RESUME! Riprendo le operazioni...")
						 Stopped = false  
						if(  MoveInProgress  
						 ){CommUtils.outcyan("cargorobot | Riprendo il movimento interrotto verso ($TargetX, $TargetY)...")
						request("moverobot", "moverobot($TargetX,$TargetY,$StepTime)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_reply", cond=doswitchGuarded({ MoveInProgress  
					}) )
					transition( edgeName="goto",targetState="waiting", cond=doswitchGuarded({! ( MoveInProgress  
					) }) )
				}	 
			}
		}
} 
