/* Generated by AN DISI Unibo */ 
package it.unibo.sonarmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(4000) 
						CommUtils.outcyan("sonarmock | Container placed -> Emitting sonardata(30)")
						emit("sonardata", "distance(30)" ) 
						delay(10000) 
						CommUtils.outred("sonarmock | Sonar measures D > DFREE (200) -> Emitting sonardata(200)")
						emit("sonardata", "distance(200)" ) 
						delay(6000) 
						CommUtils.outgreen("sonarmock | Sonar measures D <= DFREE (30) -> Emitting sonardata(30)")
						emit("sonardata", "distance(30)" ) 
						delay(10000) 
						CommUtils.outcyan("sonarmock | IOPort free -> Emitting sonardata(80)")
						emit("sonardata", "distance(80)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="cycle", cond=doswitch() )
				}	 
				state("cycle") { //this:State
					action { //it:State
						delay(8000) 
						CommUtils.outcyan("sonarmock [cycle] | Container placed -> Emitting sonardata(30)")
						emit("sonardata", "distance(30)" ) 
						delay(8000) 
						CommUtils.outcyan("sonarmock [cycle] | IOPort free -> Emitting sonardata(80)")
						emit("sonardata", "distance(80)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="cycle", cond=doswitch() )
				}	 
			}
		}
} 
