/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var IOPortOccupied = false
		        var ServiceWorking = true
		        var CargoState     = "disengaged"
		        var ReservedSlotId = -1
		        val StepTime       = 335
		        var OutOfServicePendingStart = -1L  
		        var ContainerPendingStart    = -1L  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | STARTED")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | DISENGAGED: waiting for requests...")
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t01",targetState="handle_sonar",cond=whenDispatch("incoming_sonar"))
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | ENGAGED: evaluating next step...")
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					}) )
					transition( edgeName="goto",targetState="wait_for_container", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					) }) )
				}	 
				state("wait_for_container") { //this:State
					action { //it:State
						CommUtils.outcyan("cargoservice | Waiting for container to be deposited on IOPort (Max 30s)...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handle_deposit_timeout",cond=whenDispatch("deposit_timeout_msg"))
					transition(edgeName="t03",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t04",targetState="handle_sonar",cond=whenDispatch("incoming_sonar"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  CargoState == "engaged" || !ServiceWorking || IOPortOccupied  
						 ){answer("load_request", "load_retrylater", "loadRetryLater(none)"   )  
						}
						else
						 { val SlotId = Hold.reserveSlot()  
						 if(  SlotId > 0  
						  ){ 
						                     ReservedSlotId = SlotId
						                     CargoState     = "engaged" 
						                     val currentSlot = ReservedSlotId
						                     kotlinx.coroutines.GlobalScope.launch {
						                         kotlinx.coroutines.delay(30000)
						                         if (CargoState == "engaged" && !IOPortOccupied && ReservedSlotId == currentSlot) {
						                             forward("deposit_timeout_msg", "depositTimeout(none)", "cargoservice")
						                         }
						                     }
						 forward("led_ctrl", "ledCmd(blink)" ,"ledadapter" ) 
						  val SlotName = "slot$ReservedSlotId"  
						 answer("load_request", "load_accepted", "loadAccepted($SlotName)"   )  
						  val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						 updateResourceRep( statusJson  
						 )
						 }
						 else
						  {answer("load_request", "load_refused", "loadRefused(none)"   )  
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val Dist = try { payloadArg(0).toDouble().toInt() } catch(e: Exception) { payloadArg(0).toIntOrNull() ?: 0 }
								                val Now  = System.currentTimeMillis()
								                val DFree = Hold.getDfree()
								                val DFreeDiv2 = DFree / 2
								
								                if (Dist < DFreeDiv2) {
								                    if (ContainerPendingStart < 0L) {
								                        ContainerPendingStart = Now
								                    } else if (Now - ContainerPendingStart >= 3000L) {
								                        IOPortOccupied = true
								                        ContainerPendingStart = -1L
								                    }
								                } else {
								                    ContainerPendingStart = -1L
								                    IOPortOccupied = false
								                }
								
								                if (Dist > DFree) {
								                    if (ServiceWorking) {
								                        if (OutOfServicePendingStart < 0L) {
								                            OutOfServicePendingStart = Now
								                        } else if (Now - OutOfServicePendingStart >= 3000L) {
								                            ServiceWorking = false
								                            OutOfServicePendingStart = -1L
								                            println("cargoservice | Sonar D>DFREE ($Dist > $DFree) sostenuto per 3s -> OUT OF SERVICE!")
								                        }
								                    }
								                } else {
								                    OutOfServicePendingStart = -1L
								                    if (!ServiceWorking) {
								                        ServiceWorking = true
								                        println("cargoservice | Sonar D<=DFREE ($Dist <= $DFree) -> SERVICE WORKING again!")
								                    }
								                }
								
								                val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)
								updateResourceRep( statusJson  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					}) )
					transition( edgeName="goto",targetState="returnToState", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					) }) )
				}	 
				state("returnToState") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("do_robot_job") { //this:State
					action { //it:State
						 discardMessages = true  
						CommUtils.outmagenta("cargoservice | Container inside area! Robot moving to IOPort (4,0)...")
						request("moverobot", "moverobot(4,0,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="pick_container",cond=whenReply("moverobotdone"))
					transition(edgeName="t06",targetState="pick_container_after_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("pick_container_after_fail") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | WARNING: Robot move failed, proceeding anyway...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="pick_container", cond=doswitch() )
				}	 
				state("pick_container") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Robot at IOPort (4,0). Container picked up.")
						 IOPortOccupied = false  
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						CommUtils.outmagenta("cargoservice | Moving container to slot5 (2,5) for marking...")
						request("moverobot", "moverobot(2,5,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="mark_container",cond=whenReply("moverobotdone"))
					transition(edgeName="t08",targetState="mark_container_after_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("mark_container_after_fail") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | WARNING: Robot move failed, proceeding to marking...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="mark_container", cond=doswitch() )
				}	 
				state("mark_container") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | At slot5. Asking markerdevice to mark container...")
						request("mark_container", "markContainer(none)" ,"markerdevice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="move_to_reserved_slot",cond=whenReply("marking_done"))
				}	 
				state("move_to_reserved_slot") { //this:State
					action { //it:State
						 
						            val DestX = Hold.getSlotX(ReservedSlotId)
						            val DestY = Hold.getSlotY(ReservedSlotId)
						CommUtils.outmagenta("cargoservice | Marked! Moving container to slot$ReservedSlotId ($DestY, $DestX)...")
						request("moverobot", "moverobot($DestY,$DestX,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="return_home",cond=whenReply("moverobotdone"))
					transition(edgeName="t011",targetState="return_home_after_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("return_home_after_fail") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | WARNING: Move to slot failed, forcing return home...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="return_home", cond=doswitch() )
				}	 
				state("return_home") { //this:State
					action { //it:State
						 Hold.occupySlot(ReservedSlotId)  
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						 
						            val HomeX = Hold.getHomeX()
						            val HomeY = Hold.getHomeY()
						CommUtils.outmagenta("cargoservice | Returning robot to HOME ($HomeY, $HomeX)...")
						request("moverobot", "moverobot($HomeY,$HomeX,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="finish_job",cond=whenReply("moverobotdone"))
					transition(edgeName="t013",targetState="handle_home_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("finish_job") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Job finished successfully!")
						 
						            discardMessages = false
						            CargoState = "disengaged"
						            ReservedSlotId = -1
						forward("led_ctrl", "ledCmd(off)" ,"ledadapter" ) 
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_home_fail") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | Robot failed to return home. Resetting state...")
						 
						            discardMessages = false
						            CargoState = "disengaged"
						            ReservedSlotId = -1
						forward("led_ctrl", "ledCmd(off)" ,"ledadapter" ) 
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_deposit_timeout") { //this:State
					action { //it:State
						if(  CargoState == "engaged" && !IOPortOccupied  
						 ){CommUtils.outred("cargoservice | Deposit timeout! Freeing reserved slot$ReservedSlotId.")
						 
						                discardMessages = false
						                Hold.freeSlot(ReservedSlotId) 
						                CargoState = "disengaged"
						                ReservedSlotId = -1
						forward("led_ctrl", "ledCmd(off)" ,"ledadapter" ) 
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({ CargoState == "disengaged"  
					}) )
					transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({! ( CargoState == "disengaged"  
					) }) )
				}	 
			}
		}
} 
