/* Generated by AN DISI Unibo */ 
package it.unibo.hold

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Hold ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var Slots = intArrayOf(0, 0, 0, 0)
		        
		        fun getFreeSlot(): Int {
		            for (i in 0..3) {
		                if (Slots[i] == 0) return i + 1
		            }
		            return -1
		        }
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("hold | STARTED")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_get_slot",cond=whenRequest("get_slot"))
					transition(edgeName="t01",targetState="handle_free_slot",cond=whenDispatch("free_slot"))
				}	 
				state("handle_get_slot") { //this:State
					action { //it:State
						 val SlotId = getFreeSlot()  
						if(  SlotId != -1  
						 ){ Slots[SlotId - 1] = 1  
						answer("get_slot", "slot_reserved", "slotReserved($SlotId)"   )  
						}
						else
						 {answer("get_slot", "hold_full", "holdFull(none)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handle_free_slot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("freeSlot(SLOTID)"), Term.createTerm("freeSlot(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val id = payloadArg(0).toInt()  
								 Slots[id - 1] = 0  
								CommUtils.outgreen("hold | Freed slot$id")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
