/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargorobot | STARTED (Wrapper di dominio per robotsmart26)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="handle_move",cond=whenRequest("moverobot"))
				}	 
				state("handle_move") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobot(TARGETX,TARGETY,STEPTIME)"), Term.createTerm("moverobot(X,Y,TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                val Tx = payloadArg(0)
								                val Ty = payloadArg(1)
								                val StepTime = payloadArg(2)
								CommUtils.outcyan("cargorobot | Inoltro comando moverobot($Tx, $Ty, $StepTime) a robotsmart26...")
								request("moverobot", "moverobot($Tx,$Ty,$StepTime)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="handle_move_done",cond=whenReply("moverobotdone"))
					transition(edgeName="t014",targetState="handle_move_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("handle_move_done") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotok(ARG)"), Term.createTerm("moverobotok(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("cargorobot | Movimento completato da robotsmart26. Rispondo al cargoservice...")
								answer("moverobot", "moverobotdone", "moverobotok(done)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handle_move_failed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PL,TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outred("cargorobot | Fallimento movimento in robotsmart26. Rispondo failure al cargoservice...")
								answer("moverobot", "moverobotfailed", "moverobotfailed(obstacle,0)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
