/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var IOPortOccupied = false
		        var ServiceWorking = true
		        var CargoState     = "disengaged"
		        var ReservedSlotId = -1
		        val StepTime       = 335
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | STARTED")
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | DISENGAGED: waiting for requests...")
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t01",targetState="handle_sonar",cond=whenEvent("sonardata"))
					transition(edgeName="t02",targetState="update_service",cond=whenDispatch("set_service_status"))
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | ENGAGED: waiting for container deposit or robot completion...")
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					}) )
					transition( edgeName="goto",targetState="wait_for_container", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					) }) )
				}	 
				state("wait_for_container") { //this:State
					action { //it:State
						delay(2000) 
						CommUtils.outcyan("cargoservice [sim] | Container automatically dropped into sensor_area (IOPort)!")
						 IOPortOccupied = true  
						 val simStatusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( simStatusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					}) )
					transition( edgeName="goto",targetState="engaged_loop", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					) }) )
				}	 
				state("engaged_loop") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engaged_loop", 
				 	 					  scope, context!!, "local_tout_"+name+"_engaged_loop", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="handle_deposit_timeout",cond=whenTimeout("local_tout_"+name+"_engaged_loop"))   
					transition(edgeName="t04",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t05",targetState="handle_sonar",cond=whenEvent("sonardata"))
					transition(edgeName="t06",targetState="update_service",cond=whenDispatch("set_service_status"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  CargoState == "engaged" || !ServiceWorking || IOPortOccupied  
						 ){answer("load_request", "load_retrylater", "loadRetryLater(none)"   )  
						}
						else
						 { val SlotId = Hold.reserveSlot()  
						 if(  SlotId > 0  
						  ){ 
						                     ReservedSlotId = SlotId
						                     CargoState     = "engaged" 
						 forward("led_ctrl", "ledCmd(blink)" ,"ledmock" ) 
						  val SlotName = "slot$ReservedSlotId"  
						 answer("load_request", "load_accepted", "loadAccepted($SlotName)"   )  
						  val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						 updateResourceRep( statusJson  
						 )
						 }
						 else
						  {answer("load_request", "load_refused", "loadRefused(none)"   )  
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toInt()  
								if(  Dist < 50  
								 ){ IOPortOccupied = true  
								}
								else
								 { IOPortOccupied = false  
								 }
								 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
								updateResourceRep( statusJson  
								)
								if(  Dist > 150  
								 ){if(  ServiceWorking  
								 ){ ServiceWorking = false  
								CommUtils.outred("cargoservice | Sonar D > DFREE ($Dist) -> OUT OF SERVICE!")
								 val statusJson = Hold.toJson(CargoState, "Out of service", IOPortOccupied, ReservedSlotId)  
								updateResourceRep( statusJson  
								)
								}
								}
								else
								 {if(  !ServiceWorking  
								  ){ ServiceWorking = true  
								 CommUtils.outgreen("cargoservice | Sonar D <= DFREE ($Dist) -> SERVICE WORKING again!")
								  val statusJson = Hold.toJson(CargoState, "Service working", IOPortOccupied, ReservedSlotId)  
								 updateResourceRep( statusJson  
								 )
								 }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					}) )
					transition( edgeName="goto",targetState="returnToState", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					) }) )
				}	 
				state("update_service") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setServiceStatus(STATUS)"), Term.createTerm("setServiceStatus(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val status = payloadArg(0)  
								if(  status == "outofservice" && ServiceWorking  
								 ){ ServiceWorking = false  
								CommUtils.outred("cargoservice | setServiceStatus outofservice -> OUT OF SERVICE!")
								 val statusJson = Hold.toJson(CargoState, "Out of service", IOPortOccupied, ReservedSlotId)  
								updateResourceRep( statusJson  
								)
								}
								if(  status == "working" && !ServiceWorking  
								 ){ ServiceWorking = true  
								CommUtils.outgreen("cargoservice | setServiceStatus working -> SERVICE WORKING!")
								 val statusJson = Hold.toJson(CargoState, "Service working", IOPortOccupied, ReservedSlotId)  
								updateResourceRep( statusJson  
								)
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="returnToState", cond=doswitch() )
				}	 
				state("returnToState") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("do_robot_job") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Container inside sensor_area! Robot moving to IOPort (4,0) to pick it up...")
						request("moverobot", "moverobot(4,0,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="pick_container",cond=whenReply("moverobotdone"))
					transition(edgeName="t08",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("pick_container") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Robot at IOPort (4,0). Container picked up! IOPort is now FREE.")
						 IOPortOccupied = false  
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						CommUtils.outmagenta("cargoservice | Moving container to slot5 (2,5) for marking...")
						request("moverobot", "moverobot(2,5,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="mark_container",cond=whenReply("moverobotdone"))
					transition(edgeName="t010",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("mark_container") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | At slot5. Asking markerdevice to mark container...")
						request("mark_container", "markContainer(none)" ,"markerdevice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="move_to_reserved_slot",cond=whenReply("marking_done"))
				}	 
				state("move_to_reserved_slot") { //this:State
					action { //it:State
						 
						            val DestX = Hold.getSlotX(ReservedSlotId)
						            val DestY = Hold.getSlotY(ReservedSlotId)
						CommUtils.outmagenta("cargoservice | Marked! Moving container to slot$ReservedSlotId ($DestY, $DestX)...")
						request("moverobot", "moverobot($DestY,$DestX,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="return_home",cond=whenReply("moverobotdone"))
					transition(edgeName="t013",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("return_home") { //this:State
					action { //it:State
						 Hold.occupySlot(ReservedSlotId)  
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						 
						            val HomeX = Hold.getHomeX()
						            val HomeY = Hold.getHomeY()
						CommUtils.outmagenta("cargoservice | Container stored in slot$ReservedSlotId! Returning robot to HOME ($HomeY, $HomeX)...")
						request("moverobot", "moverobot($HomeY,$HomeX,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="finish_job",cond=whenReply("moverobotdone"))
					transition(edgeName="t015",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("finish_job") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Job finished successfully!")
						 
						            CargoState = "disengaged"
						            ReservedSlotId = -1
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_robot_fail") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | Robot move failed! Aborting job and returning to disengaged...")
						if(  ReservedSlotId != -1  
						 ){ Hold.freeSlot(ReservedSlotId)  
						}
						 
						            CargoState = "disengaged"
						            ReservedSlotId = -1
						            IOPortOccupied = false
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_deposit_timeout") { //this:State
					action { //it:State
						if(  CargoState == "engaged" && !IOPortOccupied  
						 ){CommUtils.outred("cargoservice | Deposit timeout! Freeing reserved slot$ReservedSlotId.")
						 Hold.freeSlot(ReservedSlotId)  
						 
						                CargoState = "disengaged"
						                ReservedSlotId = -1
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						 val statusJson = Hold.toJson(CargoState, if(ServiceWorking) "Service working" else "Out of service", IOPortOccupied, ReservedSlotId)  
						updateResourceRep( statusJson  
						)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({ CargoState == "disengaged"  
					}) )
					transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({! ( CargoState == "disengaged"  
					) }) )
				}	 
			}
		}
} 
