/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var IOPortOccupied = false
		        var ServiceWorking = true
		        var CargoState     = "disengaged"
		        var ReservedSlotId = -1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | STARTED")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | DISENGAGED: waiting for requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t01",targetState="handle_sonar",cond=whenEvent("sonardata"))
					transition(edgeName="t02",targetState="update_service",cond=whenDispatch("set_service_status"))
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | ENGAGED: waiting for container deposit...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engaged", 
				 	 					  scope, context!!, "local_tout_"+name+"_engaged", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="handle_deposit_timeout",cond=whenTimeout("local_tout_"+name+"_engaged"))   
					transition(edgeName="t04",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t05",targetState="handle_sonar",cond=whenEvent("sonardata"))
					transition(edgeName="t06",targetState="update_service",cond=whenDispatch("set_service_status"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  CargoState == "engaged" || !ServiceWorking || IOPortOccupied  
						 ){answer("load_request", "load_retrylater", "loadRetryLater(none)"   )  
						}
						else
						 {request("get_slot", "getSlot(none)" ,"hold" )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="returnToState", cond=doswitchGuarded({ CargoState == "engaged" || !ServiceWorking || IOPortOccupied  
					}) )
					transition( edgeName="goto",targetState="wait_for_slot", cond=doswitchGuarded({! ( CargoState == "engaged" || !ServiceWorking || IOPortOccupied  
					) }) )
				}	 
				state("wait_for_slot") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="accept_request",cond=whenReply("slot_reserved"))
					transition(edgeName="t08",targetState="refuse_request",cond=whenReply("hold_full"))
				}	 
				state("accept_request") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slotReserved(SLOTID)"), Term.createTerm("slotReserved(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                ReservedSlotId = payloadArg(0).toInt()
								                CargoState     = "engaged" 
								forward("led_ctrl", "ledCmd(blink)" ,"ledmock" ) 
								 val SlotName = "slot$ReservedSlotId"  
								answer("load_request", "load_accepted", "loadAccepted($SlotName)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitch() )
				}	 
				state("refuse_request") { //this:State
					action { //it:State
						answer("load_request", "load_refused", "loadRefused(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toInt()  
								if(  Dist < 50  
								 ){ IOPortOccupied = true  
								}
								else
								 { IOPortOccupied = false  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="returnToState", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged"  
					) }) )
				}	 
				state("update_service") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setServiceStatus(STATUS)"), Term.createTerm("setServiceStatus(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ServiceWorking = (payloadArg(0) == "working")  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="returnToState", cond=doswitch() )
				}	 
				state("returnToState") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("do_robot_job") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Container deposited! Moving to slot5...")
						request("robot_move", "robotMove(slot5)" ,"cargorobotmock" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="mark_container",cond=whenReply("robot_done"))
				}	 
				state("mark_container") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | At slot5. Asking markerdevice to mark...")
						request("mark_container", "markContainer(none)" ,"markerdevice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="move_to_reserved_slot",cond=whenReply("marking_done"))
				}	 
				state("move_to_reserved_slot") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Marked! Moving to slot$ReservedSlotId...")
						 val TargetSlot = "slot$ReservedSlotId"  
						request("robot_move", "robotMove($TargetSlot)" ,"cargorobotmock" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="finish_job",cond=whenReply("robot_done"))
				}	 
				state("finish_job") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Job completed!")
						 CargoState = "disengaged"  
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_deposit_timeout") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | Deposit timeout! Freeing slot.")
						 CargoState = "disengaged"  
						forward("free_slot", "freeSlot($ReservedSlotId)" ,"hold" ) 
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
