

/* ------------------------------------------
   Automatically generated by AN
   ------------------------------------------ */

package it.unibo.is.interfaces.platforms;
import it.unibo.is.interfaces.IMessage;

	public interface IMessageAndContext {
		public final String endMessage = "endOfAnswerSysMsg";
 	 	public IMessage getReceivedMessage();
	 	public void replyToCaller(String msg) throws Exception;
	 	public void replyStepToCaller(String msg) throws Exception;
	 	public void replyStepContentToCaller(String path) throws Exception;
	 	public void replyEndToCaller() throws Exception;
	 	//Works at connection level
	 	public void replyContentBareToCaller(String source, boolean isFile) throws Exception;
	}
