/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var IOPortOccupied = false
		        var ServiceWorking = true
		        var CargoState     = "disengaged"
		        var ReservedSlotId = -1
		        val StepTime       = 345
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | AVVIATO")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | LIBERO: in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t01",targetState="handle_sonar",cond=whenEvent("sonardata"))
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | IMPEGNATO: in attesa del deposito del container...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engaged", 
				 	 					  scope, context!!, "local_tout_"+name+"_engaged", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="handle_deposit_timeout",cond=whenTimeout("local_tout_"+name+"_engaged"))   
					transition(edgeName="t03",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t04",targetState="handle_sonar",cond=whenEvent("sonardata"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  CargoState == "engaged" || !ServiceWorking || IOPortOccupied  
						 ){answer("load_request", "load_retrylater", "loadRetryLater(none)"   )  
						}
						else
						 { val SlotId = Hold.reserveSlot()  
						 if(  SlotId > 0  
						  ){ 
						                     ReservedSlotId = SlotId
						                     CargoState     = "engaged" 
						 forward("led_ctrl", "ledCmd(blink)" ,"ledmock" ) 
						  val SlotName = "slot$ReservedSlotId"  
						 answer("load_request", "load_accepted", "loadAccepted($SlotName)"   )  
						 }
						 else
						  {answer("load_request", "load_refused", "loadRefused(none)"   )  
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toInt()  
								if(  Dist < 50  
								 ){ IOPortOccupied = true  
								}
								else
								 { IOPortOccupied = false  
								 }
								if(  Dist > 150  
								 ){ ServiceWorking = false  
								CommUtils.outred("cargoservice | Sonar D > DFREE ($Dist) -> Sistema FUORI SERVIZIO!")
								}
								else
								 {if(  !ServiceWorking  
								  ){CommUtils.outgreen("cargoservice | Sonar D <= DFREE ($Dist) -> Sistema di nuovo FUNZIONANTE!")
								 }
								  ServiceWorking = true  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_robot_job", cond=doswitchGuarded({ IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					}) )
					transition( edgeName="goto",targetState="returnToState", cond=doswitchGuarded({! ( IOPortOccupied && CargoState == "engaged" && ServiceWorking  
					) }) )
				}	 
				state("returnToState") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ CargoState == "engaged"  
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! ( CargoState == "engaged"  
					) }) )
				}	 
				state("do_robot_job") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Container depositato! Spostamento del robot allo slot5 (2,5) [Riga,Colonna] tramite cargorobot (wrapper robotsmart26)...")
						request("moverobot", "moverobot(2,5,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="mark_container",cond=whenReply("moverobotdone"))
					transition(edgeName="t06",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("mark_container") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargoservice | Allo slot5. Richiesta di marcatura al markerdevice...")
						request("mark_container", "markContainer(none)" ,"markerdevice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="move_to_reserved_slot",cond=whenReply("marking_done"))
				}	 
				state("move_to_reserved_slot") { //this:State
					action { //it:State
						 
						            val DestX = Hold.getSlotX(ReservedSlotId)
						            val DestY = Hold.getSlotY(ReservedSlotId)
						CommUtils.outmagenta("cargoservice | Marcato! Spostamento del container allo slot$ReservedSlotId ($DestY, $DestX) [Riga,Colonna] tramite cargorobot...")
						request("moverobot", "moverobot($DestY,$DestX,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="return_home",cond=whenReply("moverobotdone"))
					transition(edgeName="t09",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("return_home") { //this:State
					action { //it:State
						 
						            val HomeX = Hold.getHomeX()
						            val HomeY = Hold.getHomeY()
						CommUtils.outmagenta("cargoservice | Container immagazzinato! Ritorno del robot alla HOME ($HomeY,$HomeX) [Riga,Colonna] tramite cargorobot...")
						request("moverobot", "moverobot($HomeY,$HomeX,$StepTime)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="finish_job",cond=whenReply("moverobotdone"))
					transition(edgeName="t011",targetState="handle_robot_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("finish_job") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Lavoro completato!")
						 CargoState = "disengaged"  
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handle_robot_fail") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | Movimento del robot fallito!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitch() )
				}	 
				state("handle_deposit_timeout") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | Timeout del deposito! Liberazione dello slot.")
						 
						            CargoState = "disengaged" 
						            Hold.freeSlot(ReservedSlotId)
						forward("led_ctrl", "ledCmd(off)" ,"ledmock" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
