/* Generated by AN DISI Unibo */ 
package it.unibo.sonaradapter

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonaradapter ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 subscribe("sensore/sonar")  
						CommUtils.outcyan("sonaradapter | STARTED - MQTT input topic sensore/sonar")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_sonar_payload",cond=whenEvent("kernel_rawmsg"))
				}	 
				state("handle_sonar_payload") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("kernel_rawmsg(D)"), Term.createTerm("kernel_rawmsg(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val RawDistance = payloadArg(0).trim()
								                val Distance = RawDistance.toDoubleOrNull()?.toInt()
								if(  Distance != null  
								 ){emit("sonardata", "distance($Distance)" ) 
								CommUtils.outcyan("sonaradapter | MQTT sensore/sonar=$RawDistance -> sonardata distance($Distance)")
								}
								else
								 {CommUtils.outred("sonaradapter | Ignored invalid MQTT sonar payload: $RawDistance")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}

	override fun messageArrived(topic: String, msg: org.eclipse.paho.client.mqttv3.MqttMessage) {
		if (topic == "sensore/sonar") {
			try {
				val rawMsg = msg.toString()
				val m = MsgUtil.buildEvent("alien", "kernel_rawmsg", "kernel_rawmsg('$rawMsg')")
				kotlinx.coroutines.GlobalScope.launch { actor.send(m) }
			} catch (e: Exception) {
				CommUtils.outred("Sonaradapter | Error in custom messageArrived: ${e.message}")
			}
		} else {
			super.messageArrived(topic, msg)
		}
	}
} 
