/* Generated by AN DISI Unibo */ 
package it.unibo.ioportmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioportmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						// TEST 1: send the first load request while the service should be free.
						// Expected: cargoservice replies load_accepted(slotN) and ledmock receives blink.
						delay(1000) 
						CommUtils.outcyan("ioportmock | TEST 1 - Sending 1st load_request (expected load_accepted)")
						request("load_request", "loadRequest(none)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="handle_accept",cond=whenReply("load_accepted"))
					transition(edgeName="t015",targetState="handle_retry",cond=whenReply("load_retrylater"))
					transition(edgeName="t016",targetState="handle_refuse",cond=whenReply("load_refused"))
				}	 
				state("handle_accept") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	
						// TEST 2: immediately send another request while cargoservice is engaged.
						// Expected: no queue is created and cargoservice replies load_retrylater.
						delay(500) 
						CommUtils.outcyan("ioportmock | TEST 2 - Sending 2nd load_request while engaged (expected load_retrylater)")
						request("load_request", "loadRequest(none)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="handle_no_queue_ok",cond=whenReply("load_retrylater"))
					transition(edgeName="t018",targetState="handle_unexpected_accept",cond=whenReply("load_accepted"))
					transition(edgeName="t019",targetState="handle_refuse",cond=whenReply("load_refused"))
				}	 
				state("handle_no_queue_ok") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						CommUtils.outgreen("ioportmock | TEST 2 OK - request rejected with retrylater while service is engaged")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handle_unexpected_accept") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						CommUtils.outred("ioportmock | TEST 2 FAILED - request was accepted while service was already engaged")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handle_retry") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handle_refuse") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
